esphome:
  name: somfy-sniffer
  includes:
  - somfy_sniff/

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXX"

ota:
  password: "XXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Somfy-Sniffer Fallback Hotspot"
    password: "XXXXXXX"

captive_portal:
    


time:
  - platform: sntp
    id: sntp_time    

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new SomfySniffer();
    App.register_component(my_sensor);
    return {my_sensor->address_sensor, my_sensor->controlCode_sensor, my_sensor->rollingCode_sensor};



  sensors:
    - name: "somfy_address"
      force_update: True
      filters: 
        - debounce: 0.3s
    - name: "somfy_controlCode"
      force_update: True
      filters: 
        - debounce: 0.3s
    - name: "somfy_rollingCode"
      force_update: True
      filters: 
        - debounce: 0.3s
        - lambda: id(somfy_lastTimeUpdate).publish_state(std::to_string(id(sntp_time).now().timestamp)); return x; 
        


text_sensor:
  - platform: template
    name: "somfy_lastTimeUpdate"
    id: "somfy_lastTimeUpdate"


